#pragma once

#define PS2_SCANCODE_A                   0x1C
#define PS2_SCANCODE_B                   0x32
#define PS2_SCANCODE_C                   0x21
#define PS2_SCANCODE_D                   0x23
#define PS2_SCANCODE_E                   0x24
#define PS2_SCANCODE_F                   0x2B
#define PS2_SCANCODE_G                   0x34
#define PS2_SCANCODE_H                   0x33
#define PS2_SCANCODE_I                   0x43
#define PS2_SCANCODE_J                   0x3B
#define PS2_SCANCODE_K                   0x42
#define PS2_SCANCODE_L                   0x4B
#define PS2_SCANCODE_M                   0x3A
#define PS2_SCANCODE_N                   0x31
#define PS2_SCANCODE_O                   0x44
#define PS2_SCANCODE_P                   0x4D
#define PS2_SCANCODE_Q                   0x15
#define PS2_SCANCODE_R                   0x2D
#define PS2_SCANCODE_S                   0x1B
#define PS2_SCANCODE_T                   0x2C
#define PS2_SCANCODE_U                   0x3C
#define PS2_SCANCODE_V                   0x2A
#define PS2_SCANCODE_W                   0x1D
#define PS2_SCANCODE_X                   0x22
#define PS2_SCANCODE_Y                   0x35
#define PS2_SCANCODE_Z                   0x1A

#define PS2_SCANCODE_0                   0x45
#define PS2_SCANCODE_1                   0x16
#define PS2_SCANCODE_2                   0x1E
#define PS2_SCANCODE_3                   0x26
#define PS2_SCANCODE_4                   0x25
#define PS2_SCANCODE_5                   0x2E
#define PS2_SCANCODE_6                   0x36
#define PS2_SCANCODE_7                   0x3D
#define PS2_SCANCODE_8                   0x3E
#define PS2_SCANCODE_9                   0x46

#define PS2_SCANCODE_F1                  0x05
#define PS2_SCANCODE_F2                  0x06
#define PS2_SCANCODE_F3                  0x04
#define PS2_SCANCODE_F4                  0x0C
#define PS2_SCANCODE_F5                  0x03
#define PS2_SCANCODE_F6                  0x0B
#define PS2_SCANCODE_F7                  0x83
#define PS2_SCANCODE_F8                  0x0A
#define PS2_SCANCODE_F9                  0x01
#define PS2_SCANCODE_F10                 0x09
#define PS2_SCANCODE_F11                 0x78
#define PS2_SCANCODE_F12                 0x07

#define PS2_SCANCODE_TILDE               0x0E
#define PS2_SCANCODE_MINUS               0x4E
#define PS2_SCANCODE_EQUAL               0x55
#define PS2_SCANCODE_LBRACKET            0x54
#define PS2_SCANCODE_RBRACKET            0x5B
#define PS2_SCANCODE_BACK_SLASH          0x5D
#define PS2_SCANCODE_SEMICOLON           0x4C
#define PS2_SCANCODE_APOSTROPHE          0x52
#define PS2_SCANCODE_COMMA               0x41
#define PS2_SCANCODE_PERIOD              0x49

#define PS2_SCANCODE_FORWARD_SLASH       0x4A
#define PS2_SCANCODE_BACKSPACE           0x66
#define PS2_SCANCODE_SPACE               0x29
#define PS2_SCANCODE_TAB                 0x0D
#define PS2_SCANCODE_CAPS                0x58
#define PS2_SCANCODE_LSHFT               0x12
#define PS2_SCANCODE_RSHFT               0x59
#define PS2_SCANCODE_LCTRL               0x14
#define PS2_SCANCODE_RCTRL               0x14
#define PS2_SCANCODE_LALT                0x11
#define PS2_SCANCODE_RALT                0x11
#define PS2_SCANCODE_LWIN                0x1F
#define PS2_SCANCODE_RWIN                0x27
#define PS2_SCANCODE_ENTER               0x5A
#define PS2_SCANCODE_ESC                 0x76
#define PS2_SCANCODE_INSERT              0x70
#define PS2_SCANCODE_DELETE              0x71
#define PS2_SCANCODE_HOME                0x6C
#define PS2_SCANCODE_END                 0x69
#define PS2_SCANCODE_PGUP                0x7D
#define PS2_SCANCODE_PGDN                0x7A
#define PS2_SCANCODE_UARROW              0x75
#define PS2_SCANCODE_LARROW              0x6B
#define PS2_SCANCODE_DARROW              0x72
#define PS2_SCANCODE_RARROW              0x74
#define PS2_SCANCODE_NUM                 0x77

#define PS2_SCANCODE_KP_FORWARD_SLASH    0x4A
#define PS2_SCANCODE_KP_MULT             0x7C
#define PS2_SCANCODE_KP_MINUS            0x7B
#define PS2_SCANCODE_KP_PLUS             0x79
#define PS2_SCANCODE_KPEN                0x5A
#define PS2_SCANCODE_KP_PERIOD           0x71
#define PS2_SCANCODE_KP0                 0x70
#define PS2_SCANCODE_KP1                 0x69
#define PS2_SCANCODE_KP2                 0x72
#define PS2_SCANCODE_KP3                 0x7A
#define PS2_SCANCODE_KP4                 0x6B
#define PS2_SCANCODE_KP5                 0x73
#define PS2_SCANCODE_KP6                 0x74
#define PS2_SCANCODE_KP7                 0x6C
#define PS2_SCANCODE_KP8                 0x75
#define PS2_SCANCODE_KP9                 0x7D
#define PS2_SCANCODE_APPS                0x2F
#define PS2_SCANCODE_SCROLL              0x7E
