#define KEYCODE_KEY                      0x
#define KEYCODE_A                        0x
#define KEYCODE_B                        0x
#define KEYCODE_C                        0x
#define KEYCODE_D                        0x
#define KEYCODE_E                        0x
#define KEYCODE_F                        0x
#define KEYCODE_G                        0x
#define KEYCODE_H                        0x
#define KEYCODE_I                        0x
#define KEYCODE_J                        0x
#define KEYCODE_K                        0x
#define KEYCODE_L                        0x
#define KEYCODE_M                        0x
#define KEYCODE_N                        0x
#define KEYCODE_O                        0x
#define KEYCODE_P                        0x
#define KEYCODE_Q                        0x
#define KEYCODE_R                        0x
#define KEYCODE_S                        0x
#define KEYCODE_T                        0x
#define KEYCODE_U                        0x
#define KEYCODE_V                        0x
#define KEYCODE_W                        0x
#define KEYCODE_X                        0x
#define KEYCODE_Y                        0x
#define KEYCODE_Z                        0x
#define KEYCODE_0                        0x
#define KEYCODE_1                        0x
#define KEYCODE_2                        0x
#define KEYCODE_3                        0x
#define KEYCODE_4                        0x
#define KEYCODE_5                        0x
#define KEYCODE_6                        0x
#define KEYCODE_7                        0x
#define KEYCODE_8                        0x
#define KEYCODE_9                        0x
#define KEYCODE_F1                       0x
#define KEYCODE_F2                       0x
#define KEYCODE_F3                       0x
#define KEYCODE_F4                       0x
#define KEYCODE_F5                       0x
#define KEYCODE_F6                       0x
#define KEYCODE_F7                       0x
#define KEYCODE_F8                       0x
#define KEYCODE_F9                       0x
#define KEYCODE_F10                      0x
#define KEYCODE_F11                      0x
#define KEYCODE_F12                      0x
#define KEYCODE_`                        0x
#define KEYCODE_-                        0x
#define KEYCODE_=                        0x
#define KEYCODE_[                        0x
#define KEYCODE_]                        0x
#define KEYCODE_                         0x
#define KEYCODE_;                        0x
#define KEYCODE_'                        0x
#define KEYCODE_,                        0x
#define KEYCODE_.                        0x
#define KEYCODE_/                        0x
#define KEYCODE_BKSP                     0x
#define KEYCODE_SPACE                    0x
#define KEYCODE_TAB                      0x
#define KEYCODE_CAPS                     0x
#define KEYCODE_LSHFT                    0x
#define KEYCODE_RSHFT                    0x
#define KEYCODE_LCTRL                    0x
#define KEYCODE_RCTRL                    0x
#define KEYCODE_LALT                     0x
#define KEYCODE_RALT                     0x
#define KEYCODE_LWIN                     0x
#define KEYCODE_RWIN                     0x
#define KEYCODE_ENTER                    0x
#define KEYCODE_ESC                      0x
#define KEYCODE_INSERT                   0x
#define KEYCODE_DELETE                   0x
#define KEYCODE_HOME                     0x
#define KEYCODE_END                      0x
#define KEYCODE_PGUP                     0x
#define KEYCODE_PGDN                     0x
#define KEYCODE_UARROW                   0x
#define KEYCODE_LARROW                   0x
#define KEYCODE_DARROW                   0x
#define KEYCODE_RARROW                   0x
#define KEYCODE_NUM                      0x
#define KEYCODE_KP/                      0x
#define KEYCODE_KP*                      0x
#define KEYCODE_KP-                      0x
#define KEYCODE_KP+                      0x
#define KEYCODE_KPEN                     0x
#define KEYCODE_KP.                      0x
#define KEYCODE_KP0                      0x
#define KEYCODE_KP1                      0x
#define KEYCODE_KP2                      0x
#define KEYCODE_KP3                      0x
#define KEYCODE_KP4                      0x
#define KEYCODE_KP5                      0x
#define KEYCODE_KP6                      0x
#define KEYCODE_KP7                      0x
#define KEYCODE_KP8                      0x
#define KEYCODE_KP9                      0x
#define KEYCODE_APPS                     0x
#define KEYCODE_PRNTSCRN                 0x
#define KEYCODE_SCROLL                   0x
#define KEYCODE_PAUSE                    0x
